import React from 'react';
import { Recommendation, ResumeData } from '../types';
import JobCard from './JobCard';
import { User, Download, Award, BookOpen } from 'lucide-react';
import { jsPDF } from 'jspdf';

interface ResultsViewProps {
  resume: ResumeData;
  recommendations: Recommendation[];
  onReset: () => void;
}

const ResultsView: React.FC<ResultsViewProps> = ({ resume, recommendations, onReset }) => {
  
  const handleExportPDF = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    
    // Header
    doc.setFillColor(79, 70, 229); // Indigo 600
    doc.rect(0, 0, pageWidth, 24, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(18);
    doc.setFont('helvetica', 'bold');
    doc.text("JobMatch AI - Candidate Report", 20, 16);
    
    let y = 40;
    
    // Candidate Profile Section
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text("Candidate Profile", 20, y);
    y += 8;
    
    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    doc.text(`Name: ${resume.name}`, 20, y);
    doc.text(`Email: ${resume.email}`, 120, y);
    y += 6;
    doc.text(`Experience: ${resume.experience_years} years`, 20, y);
    y += 10;
    
    doc.setFont('helvetica', 'bold');
    doc.text("Top Skills:", 20, y);
    doc.setFont('helvetica', 'normal');
    const skillsStr = resume.skills.join(", ");
    const splitSkills = doc.splitTextToSize(skillsStr, 160);
    doc.text(splitSkills, 45, y);
    y += splitSkills.length * 5 + 10;

    // Divider
    doc.setDrawColor(220, 220, 220);
    doc.setLineWidth(0.5);
    doc.line(20, y, pageWidth - 20, y);
    y += 15;
    
    // Recommendations Section
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(79, 70, 229);
    doc.text("Top Recommended Jobs", 20, y);
    y += 15;
    
    recommendations.forEach((rec, i) => {
      // Check for page break
      if (y > 260) {
        doc.addPage();
        y = 20;
      }
      
      const { job, score, match_details } = rec;
      
      // Job Title & Match Score
      doc.setFontSize(12);
      doc.setFont('helvetica', 'bold');
      doc.setTextColor(0, 0, 0);
      doc.text(`${i + 1}. ${job.title}`, 20, y);
      
      const scoreText = `${Math.round(score * 100)}% Match`;
      doc.setFontSize(10);
      doc.setTextColor(score >= 0.7 ? 21 : 220, score >= 0.7 ? 128 : 38, score >= 0.7 ? 61 : 38); // Green or Red-ish
      doc.text(scoreText, pageWidth - 20 - doc.getTextWidth(scoreText), y);
      
      y += 5;
      
      // Company Info
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100, 100, 100);
      doc.text(`${job.company} • ${job.location}`, 20, y);
      y += 7;
      
      // Reasoning
      doc.setFontSize(10);
      doc.setTextColor(60, 60, 60);
      const reasonLabel = "Analysis: ";
      doc.setFont('helvetica', 'bold');
      doc.text(reasonLabel, 20, y);
      
      doc.setFont('helvetica', 'italic');
      const reasonText = match_details.reasoning;
      const splitReason = doc.splitTextToSize(reasonText, 170 - doc.getTextWidth(reasonLabel));
      doc.text(splitReason, 20 + doc.getTextWidth(reasonLabel), y);
      
      y += splitReason.length * 4 + 8;
    });
    
    // Footer
    const pageCount = doc.internal.pages.length - 1;
    for(let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - 20, 290, { align: 'right' });
        doc.text(`Generated by JobMatch AI`, 20, 290);
    }
    
    doc.save(`${resume.name.replace(/\s+/g, '_')}_Recommendations.pdf`);
  };

  return (
    <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      <div className="flex flex-col md:flex-row gap-8">
        {/* Sidebar: Resume Summary */}
        <div className="w-full md:w-1/3 space-y-6">
          <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 sticky top-24">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-lg font-bold text-gray-900">Profile Summary</h2>
              <button onClick={onReset} className="text-sm text-indigo-600 hover:text-indigo-800 font-medium">
                New Search
              </button>
            </div>

            <div className="space-y-6">
              <div className="flex items-start gap-3">
                <div className="bg-indigo-100 p-2 rounded-full">
                   <User className="w-5 h-5 text-indigo-600" />
                </div>
                <div>
                  <h3 className="font-medium text-gray-900">{resume.name}</h3>
                  <p className="text-xs text-gray-500">{resume.email}</p>
                  <p className="text-xs text-gray-500 mt-1">{resume.experience_years} Years Experience</p>
                </div>
              </div>

              <div>
                <div className="flex items-center gap-2 mb-2 text-sm font-semibold text-gray-700">
                  <Award className="w-4 h-4" />
                  <span>Top Skills</span>
                </div>
                <div className="flex flex-wrap gap-2">
                  {resume.skills.slice(0, 10).map(skill => (
                    <span key={skill} className="inline-block px-2 py-1 bg-gray-100 text-gray-700 text-xs rounded-md font-medium">
                      {skill}
                    </span>
                  ))}
                </div>
              </div>

              <div>
                <div className="flex items-center gap-2 mb-2 text-sm font-semibold text-gray-700">
                  <BookOpen className="w-4 h-4" />
                  <span>Education</span>
                </div>
                <ul className="list-disc list-inside text-xs text-gray-600 space-y-1">
                  {resume.education.map((edu, idx) => (
                    <li key={idx}>{edu}</li>
                  ))}
                </ul>
              </div>
              
              <button 
                onClick={handleExportPDF}
                className="w-full flex items-center justify-center gap-2 border border-gray-300 bg-white text-gray-700 hover:bg-gray-50 py-2 rounded-lg text-sm font-medium transition-colors hover:border-indigo-400 hover:text-indigo-600"
              >
                <Download className="w-4 h-4" />
                Export PDF Report
              </button>
            </div>
          </div>
        </div>

        {/* Main: Recommendations */}
        <div className="w-full md:w-2/3 space-y-6">
          <div className="flex items-center justify-between">
            <div>
              <h2 className="text-2xl font-bold text-gray-900">Top Recommendations</h2>
              <p className="text-gray-500 text-sm">Based on semantic match & skill overlap</p>
            </div>
            <div className="hidden sm:block text-sm text-gray-500">
              Showing {recommendations.length} jobs
            </div>
          </div>

          <div className="space-y-4">
            {recommendations.map((rec, index) => (
              <JobCard key={rec.job.job_id} recommendation={rec} rank={index + 1} />
            ))}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ResultsView;